### ISSUE TITLE
Require cycle error is it important?

### ISSUE THREAD

**Issue by emrahc** [kanzitelli/expo-starter#15]
Hello i get this errors in starter

```
Require cycle: src/services/index.tsx -> src/services/onStart.ts -> src/stores/index.tsx -> src/stores/ui.ts -> src/services/index.tsx

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
at node_modules/metro-runtime/src/polyfills/require.js:117:6 in metroRequire
at http://192.168.28.85:8081/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:231795:29 in anonymous
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at node_modules/metro-runtime/src/polyfills/require.js:210:35 in guardedLoadModule
at node_modules/metro-runtime/src/polyfills/require.js:128:23 in metroRequire
at http://192.168.28.85:8081/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:230364:23 in anonymous
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at node_modules/metro-runtime/src/polyfills/require.js:210:35 in guardedLoadModule
at node_modules/metro-runtime/src/polyfills/require.js:128:23 in metroRequire
at src/services/onStart.ts:3:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at node_modules/metro-runtime/src/polyfills/require.js:210:35 in guardedLoadModule
at node_modules/metro-runtime/src/polyfills/require.js:128:23 in metroRequire
at src/services/index.tsx:3:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at node_modules/metro-runtime/src/polyfills/require.js:210:35 in guardedLoadModule
at node_modules/metro-runtime/src/polyfills/require.js:128:23 in metroRequire
at src/screens/main.tsx:7:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at node_modules/metro-runtime/src/polyfills/require.js:210:35 in guardedLoadModule
at node_modules/metro-runtime/src/polyfills/require.js:128:23 in metroRequire
at src/screens/index.ts:3:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at node_modules/metro-runtime/src/polyfills/require.js:210:35 in guardedLoadModule
at node_modules/metro-runtime/src/polyfills/require.js:128:23 in metroRequire
at src/app.tsx:5:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at node_modules/metro-runtime/src/polyfills/require.js:210:35 in guardedLoadModule
at node_modules/metro-runtime/src/polyfills/require.js:128:23 in metroRequire
at App.tsx:7:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at node_modules/metro-runtime/src/polyfills/require.js:210:35 in guardedLoadModule
at node_modules/metro-runtime/src/polyfills/require.js:128:23 in metroRequire
at node_modules/expo/AppEntry.js:3:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at node_modules/metro-runtime/src/polyfills/require.js:201:44 in guardedLoadModule
at node_modules/metro-runtime/src/polyfills/require.js:128:23 in metroRequire
at http://192.168.28.85:8081/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:239353:3 in global

```

```
RCTBridge required dispatch_sync to load RNGestureHandlerModule. This may lead to deadlocks
- ... 6 more stack frames from framework internals
```

I am not sure if they are important errors.

Thanks

**Comment by kanzitelli** [comment]
Hey @emrahc. They're not errors, just warnings which can be ignored for now. They don't cause any crashes or so.
