### ISSUE TITLE
expo production build error

### ISSUE THREAD

**Issue by mardo** [kanzitelli/expo-starter#47]
Hello! I am having an issue creating a production build for android in my app.

I also tried creating a brand new code base with `npx cli-rn new newProject` and had the same issue without modifying the generated code.

I'm running `eas build --platform android`, and the build fails with these logs at the end:

```
> Task :app:createBundleReleaseJsAndAssets
[stderr] 
error node_modules/react-native-gesture-handler/src/handlers/gestures/GestureDetector.tsx: /home/expo/workingdir/build/node_modules/react-native-gesture-handler/src/handlers/gestures/GestureDetector.tsx: /home/expo/workingdir/build/node_modules/react-native-gesture-handler/src/handlers/gestures/GestureDetector.tsx: helperSkipTransparentExpressionWrappers.skipTransparentExprWrapperNodes is not a function
TypeError: /home/expo/workingdir/build/node_modules/react-native-gesture-handler/src/handlers/gestures/GestureDetector.tsx: /home/expo/workingdir/build/node_modules/react-native-gesture-handler/src/handlers/gestures/GestureDetector.tsx: helperSkipTransparentExpressionWrappers.skipTransparentExprWrapperNodes is not a function
at transform (/home/expo/workingdir/build/node_modules/@babel/plugin-proposal-optional-chaining/lib/index.js:123:59)
at PluginPass.OptionalCallExpression|OptionalMemberExpression (/home/expo/workingdir/build/node_modules/@babel/plugin-proposal-optional-chaining/lib/index.js:206:9)
at newFn (/home/expo/workingdir/build/node_modules/@babel/traverse/lib/visitors.js:149:21)
at NodePath._call (/home/expo/workingdir/build/node_modules/@babel/traverse/lib/path/context.js:45:20)
at NodePath.call (/home/expo/workingdir/build/node_modules/@babel/traverse/lib/path/context.js:35:17)
at NodePath.visit (/home/expo/workingdir/build/node_modules/@babel/traverse/lib/path/context.js:80:31)
at TraversalContext.visitQueue (/home/expo/workingdir/build/node_modules/@babel/traverse/lib/context.js:86:16)
    at TraversalContext.visitSingle (/home/expo/workingdir/build/node_modules/@babel/traverse/lib/context.js:65:19)
    at TraversalContext.visit (/home/expo/workingdir/build/node_modules/@babel/traverse/lib/context.js:109:19)
    at traverseNode (/home/expo/workingdir/build/node_modules/@babel/traverse/lib/traverse-node.js:18:17)
    at NodePath.visit (/home/expo/workingdir/build/node_modules/@babel/traverse/lib/path/context.js:86:52)
at TraversalContext.visitQueue (/home/expo/workingdir/build/node_modules/@babel/traverse/lib/context.js:86:16)
    at TraversalContext.visitMultiple (/home/expo/workingdir/build/node_modules/@babel/traverse/lib/context.js:61:17)
    at TraversalContext.visit (/home/expo/workingdir/build/node_modules/@babel/traverse/lib/context.js:107:19)
    at traverseNode (/home/expo/workingdir/build/node_modules/@babel/traverse/lib/traverse-node.js:18:17)
    at NodePath.visit (/home/expo/workingdir/build/node_modules/@babel/traverse/lib/path/context.js:86:52)
    at TraversalContext.visitQueue (/home/expo/workingdir/build/node_modules/@babel/traverse/lib/context.js:86:16)
    at TraversalContext.visitSingle (/home/expo/workingdir/build/node_modules/@babel/traverse/lib/context.js:65:19)
    at TraversalContext.visit (/home/expo/workingdir/build/node_modules/@babel/traverse/lib/context.js:109:19)
    at traverseNode (/home/expo/workingdir/build/node_modules/@babel/traverse/lib/traverse-node.js:18:17)
    at NodePath.visit (/home/expo/workingdir/build/node_modules/@babel/traverse/lib/path/context.js:86:52)
    at TraversalContext.visitQueue (/home/expo/workingdir/build/node_modules/@babel/traverse/lib/context.js:86:16)
    at TraversalContext.visitMultiple (/home/expo/workingdir/build/node_modules/@babel/traverse/lib/context.js:61:17)
    at TraversalContext.visit (/home/expo/workingdir/build/node_modules/@babel/traverse/lib/context.js:107:19)
    at traverseNode (/home/expo/workingdir/build/node_modules/@babel/traverse/lib/traverse-node.js:18:17)
    at NodePath.visit (/home/expo/workingdir/build/node_modules/@babel/traverse/lib/path/context.js:86:52)
    at TraversalContext.visitQueue (/home/expo/workingdir/build/node_modules/@babel/traverse/lib/context.js:86:16)
    at TraversalContext.visitSingle (/home/expo/workingdir/build/node_modules/@babel/traverse/lib/context.js:65:19)
    at TraversalContext.visit (/home/expo/workingdir/build/node_modules/@babel/traverse/lib/context.js:109:19)
    at traverseNode (/home/expo/workingdir/build/node_modules/@babel/traverse/lib/traverse-node.js:18:17)
    at NodePath.visit (/home/expo/workingdir/build/node_modules/@babel/traverse/lib/path/context.js:86:52)
    at TraversalContext.visitQueue (/home/expo/workingdir/build/node_modules/@babel/traverse/lib/context.js:86:16)
    at TraversalContext.visitSingle (/home/expo/workingdir/build/node_modules/@babel/traverse/lib/context.js:65:19)
    at TraversalContext.visit (/home/expo/workingdir/build/node_modules/@babel/traverse/lib/context.js:109:19)
    at traverseNode (/home/expo/workingdir/build/node_modules/@babel/traverse/lib/traverse-node.js:18:17)
    at NodePath.visit (/home/expo/workingdir/build/node_modules/@babel/traverse/lib/path/context.js:86:52)
    at TraversalContext.visitQueue (/home/expo/workingdir/build/node_modules/@babel/traverse/lib/context.js:86:16)
    at TraversalContext.visitMultiple (/home/expo/workingdir/build/node_modules/@babel/traverse/lib/context.js:61:17)
    at TraversalContext.visit (/home/expo/workingdir/build/node_modules/@babel/traverse/lib/context.js:107:19)
    at traverseNode (/home/expo/workingdir/build/node_modules/@babel/traverse/lib/traverse-node.js:18:17)
    at NodePath.visit (/home/expo/workingdir/build/node_modules/@babel/traverse/lib/path/context.js:86:52)
    at TraversalContext.visitQueue (/home/expo/workingdir/build/node_modules/@babel/traverse/lib/context.js:86:16)
    at TraversalContext.visitSingle (/home/expo/workingdir/build/node_modules/@babel/traverse/lib/context.js:65:19)
    at TraversalContext.visit (/home/expo/workingdir/build/node_modules/@babel/traverse/lib/context.js:109:19)
    at traverseNode (/home/expo/workingdir/build/node_modules/@babel/traverse/lib/traverse-node.js:18:17)
    at traverse (/home/expo/workingdir/build/node_modules/@babel/traverse/lib/index.js:49:34)
    at transformFile (/home/expo/workingdir/build/node_modules/@babel/core/lib/transformation/index.js:81:29)
    at transformFile.next (<anonymous>)
    at run (/home/expo/workingdir/build/node_modules/@babel/core/lib/transformation/index.js:24:12)
> Task :app:createBundleReleaseJsAndAssets FAILED
w: Detected multiple Kotlin daemon sessions at build/kotlin/sessions
Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings
[stderr] 
FAILURE: Build completed with 3 failures.
[stderr] 
1: Task failed with an exception.
[stderr] 
-----------
[stderr] 
* What went wrong:
[stderr] 
Execution failed for task ':expo-updates:createReleaseExpoManifest'.
[stderr] 
> Process 'command 'node'' finished with non-zero exit value 1
[stderr] 
* Try:
[stderr] 
> Run with --stacktrace option to get the stack trace.
[stderr] 
> Run with --info or --debug option to get more log output.
[stderr] 
> Run with --scan to get full insights.
[stderr] 
==============================================================================
[stderr] 
2: Task failed with an exception.
[stderr] 
-----------
[stderr] 
* What went wrong:
[stderr] 
java.lang.StackOverflowError (no error message)
[stderr] 
* Try:
[stderr] 
> Run with --stacktrace option to get the stack trace.
[stderr] 
> Run with --info or --debug option to get more log output.
[stderr] 
> Run with --scan to get full insights.
[stderr] 
==============================================================================
[stderr] 
3: Task failed with an exception.
[stderr] 
-----------
[stderr] 
* What went wrong:
[stderr] 
Execution failed for task ':app:createBundleReleaseJsAndAssets'.
[stderr] 
> Process 'command 'node'' finished with non-zero exit value 1
[stderr] 
* Try:
[stderr] 
> Run with --stacktrace option to get the stack trace.
[stderr] 
> Run with --info or --debug option to get more log output.
[stderr] 
> Run with --scan to get full insights.
[stderr] 
==============================================================================
[stderr] 
* Get more help at https://help.gradle.org
[stderr] 
BUILD FAILED in 5m 39s
298 actionable tasks: 298 executed
Error: Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.
```

Any help is greatly appreciated! Thanks!

**Comment by mardo** [comment]
Removing `"@babel/plugin-proposal-export-namespace-from"` from `plugins` in `babel.config.js` fixes the build problem.

Looks like adding that is required for web support, which I don't need for the app I'm building, so it is fine for me to remove it. However, looks like still an issue if you're interested in web support.
